<!DOCTYPE html>

<html>

<head>

<meta charset="utf-8" />
<meta name="generator" content="pandoc" />
<meta http-equiv="X-UA-Compatible" content="IE=EDGE" />


<meta name="author" content="Jack Werner" />


<title>What is the Dollar Value of the Tenth Draft Pick?</title>

<script src="site_libs/jquery-3.6.0/jquery-3.6.0.min.js"></script>
<meta name="viewport" content="width=device-width, initial-scale=1" />
<link href="site_libs/bootstrap-3.3.5/css/bootstrap.min.css" rel="stylesheet" />
<script src="site_libs/bootstrap-3.3.5/js/bootstrap.min.js"></script>
<script src="site_libs/bootstrap-3.3.5/shim/html5shiv.min.js"></script>
<script src="site_libs/bootstrap-3.3.5/shim/respond.min.js"></script>
<style>h1 {font-size: 34px;}
       h1.title {font-size: 38px;}
       h2 {font-size: 30px;}
       h3 {font-size: 24px;}
       h4 {font-size: 18px;}
       h5 {font-size: 16px;}
       h6 {font-size: 12px;}
       code {color: inherit; background-color: rgba(0, 0, 0, 0.04);}
       pre:not([class]) { background-color: white }</style>
<script src="site_libs/navigation-1.1/tabsets.js"></script>
<link href="site_libs/highlightjs-9.12.0/default.css" rel="stylesheet" />
<script src="site_libs/highlightjs-9.12.0/highlight.js"></script>

<style type="text/css">
  code{white-space: pre-wrap;}
  span.smallcaps{font-variant: small-caps;}
  span.underline{text-decoration: underline;}
  div.column{display: inline-block; vertical-align: top; width: 50%;}
  div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
  ul.task-list{list-style: none;}
    </style>

<style type="text/css">code{white-space: pre;}</style>
<script type="text/javascript">
if (window.hljs) {
  hljs.configure({languages: []});
  hljs.initHighlightingOnLoad();
  if (document.readyState && document.readyState === "complete") {
    window.setTimeout(function() { hljs.initHighlighting(); }, 0);
  }
}
</script>









<style type = "text/css">
.main-container {
  max-width: 940px;
  margin-left: auto;
  margin-right: auto;
}
img {
  max-width:100%;
}
.tabbed-pane {
  padding-top: 12px;
}
.html-widget {
  margin-bottom: 20px;
}
button.code-folding-btn:focus {
  outline: none;
}
summary {
  display: list-item;
}
details > summary > p:only-child {
  display: inline;
}
pre code {
  padding: 0;
}
</style>


<style type="text/css">
.dropdown-submenu {
  position: relative;
}
.dropdown-submenu>.dropdown-menu {
  top: 0;
  left: 100%;
  margin-top: -6px;
  margin-left: -1px;
  border-radius: 0 6px 6px 6px;
}
.dropdown-submenu:hover>.dropdown-menu {
  display: block;
}
.dropdown-submenu>a:after {
  display: block;
  content: " ";
  float: right;
  width: 0;
  height: 0;
  border-color: transparent;
  border-style: solid;
  border-width: 5px 0 5px 5px;
  border-left-color: #cccccc;
  margin-top: 5px;
  margin-right: -10px;
}
.dropdown-submenu:hover>a:after {
  border-left-color: #adb5bd;
}
.dropdown-submenu.pull-left {
  float: none;
}
.dropdown-submenu.pull-left>.dropdown-menu {
  left: -100%;
  margin-left: 10px;
  border-radius: 6px 0 6px 6px;
}
</style>

<script type="text/javascript">
// manage active state of menu based on current page
$(document).ready(function () {
  // active menu anchor
  href = window.location.pathname
  href = href.substr(href.lastIndexOf('/') + 1)
  if (href === "")
    href = "index.html";
  var menuAnchor = $('a[href="' + href + '"]');

  // mark it active
  menuAnchor.tab('show');

  // if it's got a parent navbar menu mark it active as well
  menuAnchor.closest('li.dropdown').addClass('active');

  // Navbar adjustments
  var navHeight = $(".navbar").first().height() + 15;
  var style = document.createElement('style');
  var pt = "padding-top: " + navHeight + "px; ";
  var mt = "margin-top: -" + navHeight + "px; ";
  var css = "";
  // offset scroll position for anchor links (for fixed navbar)
  for (var i = 1; i <= 6; i++) {
    css += ".section h" + i + "{ " + pt + mt + "}\n";
  }
  style.innerHTML = "body {" + pt + "padding-bottom: 40px; }\n" + css;
  document.head.appendChild(style);
});
</script>

<!-- tabsets -->

<style type="text/css">
.tabset-dropdown > .nav-tabs {
  display: inline-table;
  max-height: 500px;
  min-height: 44px;
  overflow-y: auto;
  border: 1px solid #ddd;
  border-radius: 4px;
}

.tabset-dropdown > .nav-tabs > li.active:before {
  content: "";
  font-family: 'Glyphicons Halflings';
  display: inline-block;
  padding: 10px;
  border-right: 1px solid #ddd;
}

.tabset-dropdown > .nav-tabs.nav-tabs-open > li.active:before {
  content: "&#xe258;";
  border: none;
}

.tabset-dropdown > .nav-tabs.nav-tabs-open:before {
  content: "";
  font-family: 'Glyphicons Halflings';
  display: inline-block;
  padding: 10px;
  border-right: 1px solid #ddd;
}

.tabset-dropdown > .nav-tabs > li.active {
  display: block;
}

.tabset-dropdown > .nav-tabs > li > a,
.tabset-dropdown > .nav-tabs > li > a:focus,
.tabset-dropdown > .nav-tabs > li > a:hover {
  border: none;
  display: inline-block;
  border-radius: 4px;
  background-color: transparent;
}

.tabset-dropdown > .nav-tabs.nav-tabs-open > li {
  display: block;
  float: none;
}

.tabset-dropdown > .nav-tabs > li {
  display: none;
}
</style>

<!-- code folding -->




</head>

<body>


<div class="container-fluid main-container">




<div class="navbar navbar-default  navbar-fixed-top" role="navigation">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-bs-toggle="collapse" data-target="#navbar" data-bs-target="#navbar">
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="index.html">Jack Werner Baseball Analysis</a>
    </div>
    <div id="navbar" class="navbar-collapse collapse">
      <ul class="nav navbar-nav">
        <li>
  <a href="Release-Point-Tipping.html">Does Release Point Impact wOBA?</a>
</li>
<li>
  <a href="Home-Run-Classification.html">Can We Predict Home Runs?</a>
</li>
<li>
  <a href="Tenth-Draft-Pick.html">What is the Dollar Value of the Tenth Draft Pick?</a>
</li>
      </ul>
      <ul class="nav navbar-nav navbar-right">
        
      </ul>
    </div><!--/.nav-collapse -->
  </div><!--/.container -->
</div><!--/.navbar -->

<div id="header">



<h1 class="title toc-ignore">What is the Dollar Value of the Tenth Draft Pick?</h1>
<h4 class="author">Jack Werner</h4>
<h4 class="date">2/11/2023</h4>

</div>


<div id="background" class="section level2">
<h2>Background:</h2>
<p>The purpose of this document is to set a dollar value on the 10th overall pick in the MLB Amateur Draft. My approach to solve this problem is to collect historical player performance for players drafted around the 10th pick, analyze the value they have provided during their career, and convert this value into a fantasy auction-style dollar value.</p>
</div>
<div id="collecting-data" class="section level2">
<h2>Collecting Data:</h2>
<p>This project required scraping and combining data from mulitple different sources. For historical MLB Draft data, I scraped html tables from Baseball-Reference.com using an R package called rvest. This data includes draft order, player names, and team names from every draft between 1990-2022 in order to get a sample size large enough to work with.</p>
<p>Next, I downloaded career batting and pitching data from every player between 1990 and 2022 using the FanGraphs career batting and pitching leaderboards page. I imported these into R as .csv files.</p>
</div>
<div id="calculating-career-value" class="section level2">
<h2>Calculating Career Value:</h2>
<p>Because the tenth pick in the draft includes and batters and pitchers, it is important that we are measuring value-added in a way that can be compared across all positions. For this reason, I decided to use career WAR to measure the performance of each player. We also need to standardize each players WAR to control for different playing times (or retired vs still in the league). To do this, we will create a value called WAR per 162 G = (162*WAR) / G to emulate a ‘per season average’ WAR. The number of games we use does not affect the outcome, so long as it is the same across all players. <i>More on the decision to use WAR can be found in the Discussion section below.</i></p>
<p>Although the goal of this project is to assign a dollar value to the tenth pick of the draft, there is reason to believe that the players drafted slightly before or slightly after the tenth pick are not significaltly more or less talented than the players drafted tenth. In order to control for these draft inconsistencies, I decided to compute a weighted average WAR per 162 games for players drafted between 8th and 12th instead of simply averaging the WAR per 162 games for all players drafted tenth.</p>
<p>To do this, I used a neseted for loop to find the average WAR per 162 games for each pick across all 32 years, and then weighed them according to the tenth pick at 1/3 of the average, <u>+</u>1 pick at 2/9ths each, and <u>+</u>2 picks at 1/9th each. It should be noted that we are excluding any of these player’s that have never played in the Major Leagues, because we don’t have any MLB data for them!</p>
<pre class="r"><code>#picks 8 - 12 weighted
values = c()
for(j in 8:12){
  players = c()
  for (i in 1990:2022){
    theurl &lt;- paste0(&quot;https://www.baseball-reference.com/bullpen/&quot;,i,&quot;_Amateur_Draft&quot;)
    file&lt;-read_html(theurl)
    tables&lt;-html_nodes(file, &quot;table&quot;)
    draft &lt;- html_table(tables[1], fill = TRUE)[[1]]
    players = c(players,draft[draft$Pick == j,]$Player)
  }
  wars = rbind(wrcp %&gt;% filter(Name %in% players) %&gt;% select(Name, G, WAR),pitcher_war %&gt;% filter(Name %in% players) %&gt;% select(Name, G, WAR))
  wars$war_per_162 = (162*wars$WAR) / wars$G
  print(paste0(&quot;pick &quot;,j,&quot;: &quot;,mean(wars$war_per_162)))
  values = c(values, mean(wars$war_per_162))
}</code></pre>
<pre><code>## [1] &quot;pick 8: 5.48601286806051&quot;
## [1] &quot;pick 9: 4.47331129541252&quot;
## [1] &quot;pick 10: 5.35013086112053&quot;
## [1] &quot;pick 11: 6.48614735112943&quot;
## [1] &quot;pick 12: 4.90495600457411&quot;</code></pre>
<pre class="r"><code>weights = c(1/9,2/9,3/9,2/9,1/9) 
weightedavgWAR = sum(weights*values)
print(paste0(&quot;Weighted Average WAR for the 10th pick: &quot;,weightedavgWAR))</code></pre>
<pre><code>## [1] &quot;Weighted Average WAR for the 10th pick: 5.37336430545334&quot;</code></pre>
<p>This process provided a weighted average WAR per 162 games of 5.37, which is a better estimate than (and not far off from) the true average WAR per 162 games of the tenth pick at 5.35.</p>
</div>
<div id="converting-perfomance-into-a-dollar-value" class="section level2">
<h2>Converting Perfomance into a Dollar Value:</h2>
<p>Now that we have a way to quantify the average perfomance of the tenth pick in the draft, we need to compare it to the population to understand their value.</p>
<p>Next, I calculated a Z-score for the tenth pick using the average WAR per 162 we calculated above.</p>
<pre class="r"><code>z_p10 = (weightedavgWAR - mean(wars_total$war_per_162))/sd(wars_total$war_per_162)
print(paste0(&quot;Z Score of the tenth pick: &quot;,z_p10))</code></pre>
<pre><code>## [1] &quot;Z Score of the tenth pick: 0.246153448264196&quot;</code></pre>
<p>In order convert this Z-score into a dollar value, we need to find the worst player that would still be worth drafting, i.e. the player with an average WAR per 162 games <strong>closest to</strong> but <strong>greater than</strong> the mean. In otherwords, the player with the lowest WAR per 162 above average. After this value is identified, we must convert it into a Z-Score as well.</p>
<pre class="r"><code>mean_career_war = mean(wars_total$war_per_162)
real_war_replacement = min(wars_total[wars_total$war_per_162&gt;mean_career_war,]$war_per_162)
#11.7 is the lowest a player has actually had a career war &gt; replacement
z_r = (real_war_replacement - mean(wars_total$war_per_162))/sd(wars_total$war_per_162)#.004542027
print(paste0(&quot;Z-score for the worst player worth having: &quot;,z_r)) </code></pre>
<pre><code>## [1] &quot;Z-score for the worst player worth having: 0.000805079179897499&quot;</code></pre>
<p>Now that we have calculated a Z-score for the tenth pick and the worst player worth drafting, we will use the FanGraphs Auction Calculator method to assign a dollar value for each.</p>
<p>This method takes the worst player and cements his value at $1. To get there, we will subtract his own value from itself and then add $1. Then we need to make the same calculation to all players’ values to adjust them equally. Thus, we have arrived at a dollar value for our tenth-picked player at $246.35.</p>
<pre class="r"><code>dollar_value_floor = 1000*(z_r - z_r) + 1
dollar_value_tenth = 1000*(z_p10 - z_r) + 1
dollar_value_ceiling =1000*((max(wars_total$war_per_162) - mean(wars_total$war_per_162)) / sd(wars_total$war_per_162))-z_r+1
print(paste0(&quot;Worst player&#39;s dollar value: &quot;,round(dollar_value_floor,2)))</code></pre>
<pre><code>## [1] &quot;Worst player&#39;s dollar value: 1&quot;</code></pre>
<pre class="r"><code>print(paste0(&quot;Tenth-pick dollar value: &quot;,round(dollar_value_tenth,2)))</code></pre>
<pre><code>## [1] &quot;Tenth-pick dollar value: 246.35&quot;</code></pre>
<pre class="r"><code>print(paste0(&quot;Most valuable player&#39;s dollar value: &quot;,round(dollar_value_ceiling,2)))</code></pre>
<pre><code>## [1] &quot;Most valuable player&#39;s dollar value: 5690.81&quot;</code></pre>
</div>
<div id="discussion" class="section level2">
<h2>Discussion:</h2>
<p>While $246 pales in comparison to the maximum value of $5690 (Jacob deGrom, of course…), it still speaks fairly highly of the tenth pick. Actual players around this value include Mike Piazza, Corey Seager, Nolan Arenado, Josh Hader, and Matt Chapman. This is a group of players that any team should be happy to have on their roster.</p>
<p>Interestingly, of the 18 players drafted tenth that have reached the majors, only 5 returned a higher value than $246: Ben Sheets, Tim Lincecum, Madison Bumgarner, Jon Garland, and Jaret Wright.</p>
<p>A note on the decision to use WAR: WAR is an imperfect but useful statistic. This analysis uses FanGraph’s WAR values. FanGraphs defines WAR as “an attempt by the sabermetric baseball community to summarize a player’s total contributions to their team in one statistic.” Some of the benefits to using WAR is that it can capture offensive contributions, defensive contributions, and can compare between batters and pitchers. More benefits include the fact that it allows you to compare players from different ballparks, fielding positions, and eras of the game. One drawback is that WAR is not a precise measure, rather an estimate that helps us group players roughly into levels of skill. However, WAR’s precision ultimately doesn’t hurt our analysis in a meaningful way. If this analysis were to be done with strictly batters or pitchers, one might opt to use wRC+ or FIP, respectively, and get a more accurate measure.</p>
<p>Lastly, a keen eye may notice that the tenth player’s dollar value is 246x greater than the worst player above replacement, while his z-score is 308x greater The difference comes from the fact that we reduced the worst player worth having to a value of essentially zero (plus $1 since he’s is worth <i>something</i> to us). For dollar-value purposes, we are valuing his contributions as the bare minimum, and this impacts the relationship between player’s values. One could develop an alternate method of assigning value that gives this player credit for his slim replacement value, but I (along with FanGraphs) chose not to. Another alternative method could be to set the total value of the leage at something like $100,000,000 and then use Z-scores to divide the league’s value proportionally by value.</p>
</div>




</div>

<script>

// add bootstrap table styles to pandoc tables
function bootstrapStylePandocTables() {
  $('tr.odd').parent('tbody').parent('table').addClass('table table-condensed');
}
$(document).ready(function () {
  bootstrapStylePandocTables();
});


</script>

<!-- tabsets -->

<script>
$(document).ready(function () {
  window.buildTabsets("TOC");
});

$(document).ready(function () {
  $('.tabset-dropdown > .nav-tabs > li').click(function () {
    $(this).parent().toggleClass('nav-tabs-open');
  });
});
</script>

<!-- code folding -->


<!-- dynamically load mathjax for compatibility with self-contained -->
<script>
  (function () {
    var script = document.createElement("script");
    script.type = "text/javascript";
    script.src  = "https://mathjax.rstudio.com/latest/MathJax.js?config=TeX-AMS-MML_HTMLorMML";
    document.getElementsByTagName("head")[0].appendChild(script);
  })();
</script>

</body>
</html>
